version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant"
    volumes:
      - type: volume
        source: homeassistant
        target: /config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: false
    network_mode: host
volumes:
  homeassistant:
