version: '3'
services:
  minidlna:
    image: vladgh/minidlna
    container_name: minidlna 
    restart: unless-stopped
    environment:
      MINIDLNA_MEDIA_DIR_1=A,: /media/music
      MINIDLNA_FRIENDLY_NAME: SuperTux
    volumes:
      - /home/pieter/Music:/media/music
    network_mode: host
