version: '3'
services:
  minidlna:
    image: vladgh/minidlna
    environment:
      MINIDLNA_MEDIA_DIR: /media
      MINIDLNA_FRIENDLY_NAME: Docker
    volumes:
      - /mnt/muziek:/media
    network_mode: host