version: '3'
services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/data:/app/data
    ports:
      - 8090:8080
    environment:
      - TZ=Europe/Brussels
